"""add created_at, merged_at for pull_requests

Revision ID: 21d3ab1f6a9a
Revises: 5f481c4c9c2a
Create Date: 2025-11-25 19:28:57.831510

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "21d3ab1f6a9a"
down_revision: Union[str, Sequence[str], None] = "5f481c4c9c2a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "pull_requests",
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
    )
    op.add_column(
        "pull_requests",
        sa.Column("merged_at", sa.DateTime(timezone=True), nullable=True),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("pull_requests", "merged_at")
    op.drop_column("pull_requests", "created_at")
    # ### end Alembic commands ###
