"""add default status for pr

Revision ID: a20a8028e573
Revises: 21d3ab1f6a9a
Create Date: 2025-11-25 19:52:31.774818

"""

from typing import Sequence, Union

from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = "a20a8028e573"
down_revision: Union[str, Sequence[str], None] = "21d3ab1f6a9a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "pull_requests",
        "status",
        existing_type=postgresql.ENUM(
            "open", "merged", name="pull_request_status_enum"
        ),
        server_default="open",
        existing_nullable=False,
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(
        "pull_requests",
        "status",
        existing_type=postgresql.ENUM(
            "open", "merged", name="pull_request_status_enum"
        ),
        server_default=None,
        existing_nullable=False,
    )
    # ### end Alembic commands ###
